### ISSUE TITLE
Different font for different pages.. set rules in man.css

### ISSUE THREAD

**Issue by Yalong-T** [cse110-fa21-group7/cse110-fa21-group7#56]

**Comment by Yalong-T** [comment]
![image](https://user-images.githubusercontent.com/91337079/142772149-c42c9bb9-a635-4241-a895-fd24f2e332ba.png)
![image](https://user-images.githubusercontent.com/91337079/142772154-d4ab16c9-8c89-4b48-a406-5dd3fe003a3c.png)

**Comment by vrothenbergUCSD** [comment]
This should be fixed now with 'font-family: Arial,...' in main.css
