### ISSUE TITLE
cook-book css issue, hide some recipes

### ISSUE THREAD

**Issue by Yalong-T** [cse110-fa21-group7/cse110-fa21-group7#75]

**Comment by vrothenbergUCSD** [comment]
I added some flexbox CSS so that recipe cards wrap down into lower rows.  The cards are still too big for mobile though.

**Comment by Yalong-T** [comment]
![image](https://user-images.githubusercontent.com/91337079/142914127-3407a7c0-d23e-4510-be33-b8ce4918adc6.png)
